# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DIGITDB
    ports:
      - "5432:5432"  # Exposing port 5432 for database access
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persisting data
    networks:
      - mynetwork
    restart: always  # Restart policy in case the container stops unexpectedly

# Named volume for persisting PostgreSQL data
volumes:
  pg_data:

# Networks (optional if you plan to connect this container to other containers)
networks:
  mynetwork:
    driver: bridge

  # db:
  #   image: postgres
  #   restart: always
  #   # set shared memory limit when using docker-compose
  #   shm_size: 128mb
  #   # or set shared memory limit when deploy via swarm stack
  #   #volumes:
  #   #  - type: tmpfs
  #   #    target: /dev/shm
  #   #    tmpfs:
  #   #      size: 134217728 # 128*2^20 bytes = 128Mb
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: dbadmin
  #   ports:
  #     - 5432:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
